### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by MyVanitar** [niksoc/earthquake#1]
Hi

Where can I download the dataset of earthquake events?

I see your dataset, but I want to focus on a specific geographic region, such as a country.

**Comment by niksoc** [comment]
http://ds.iris.edu/ieb

**Comment by MyVanitar** [comment]
Thank you very much. may I ask you how can I download the data as you did?

**Comment by MyVanitar** [comment]
Oh, thank you, I just found it. Right side of the screen and other formats
