### ISSUE TITLE
keras representation

### ISSUE THREAD

**Issue by MyVanitar** [niksoc/earthquake#2]
Hello,

is it possible for you to re-write the code using Keras? I tried to do the same work as you did but I can not get good results.

Besides, May I ask you the errors of variables? I mean Timestamp, Lat, Lon ... and so on

Besides, I seems one of the used libraries is available for Linux only.

**Comment by MyVanitar** [comment]
I mean the model representation in Keras, not the whole code

**Comment by niksoc** [comment]
hey,
I wasn't getting good results either. On the contrary the r squared scores of every variable except Timestamp were negative.
